package org.selimsahin.entity;

/**
 * @author selimsahindev
 */
public class Company {
    private Long id;
    private String name;
    private String workArea;

    public Company() {
        // no-arg constructor
    }

    public Company(String name, String workArea) {
        this.id = null; // Will be generated by the repository.
        this.name = name;
        this.workArea = workArea;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getWorkArea() {
        return workArea;
    }

    public void setWorkArea(String workArea) {
        this.workArea = workArea;
    }

    @Override
    public String toString() {
        return "Company{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", workArea='" + workArea + '\'' +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Company)) {
            return false;
        }

        Company company = (Company) o;

        if (id != null ? !id.equals(company.id) : company.id != null) {
            return false;
        }
        if (name != null ? !name.equals(company.name) : company.name != null) {
            return false;
        }
        return workArea != null ? workArea.equals(company.workArea) : company.workArea == null;
    }

    @Override
    public int hashCode() {
        int result = id != null ? id.hashCode() : 0;
        result = 31 * result + (name != null ? name.hashCode() : 0);
        result = 31 * result + (workArea != null ? workArea.hashCode() : 0);
        return result;
    }
}
