package org.selimsahin.entity;

import java.time.LocalDate;

/**
 * @author selimsahindev
 */
public class Invoice {
    private Long id;
    private String description;
    private double amount;
    private LocalDate date;
    private Customer customer;
    private Company company;

    public Invoice() {
        // no-arg constructor
    }

    public Invoice(String description, double amount, LocalDate date, Customer customer, Company company) {
        this.id = null; // Will be generated by the repository.
        this.description = description;
        this.amount = amount;
        this.date = date;
        this.customer = customer;
        this.company = company;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public double getAmount() {
        return amount;
    }

    public void setAmount(double amount) {
        this.amount = amount;
    }

    public LocalDate getDate() {
        return date;
    }

    public void setDate(LocalDate date) {
        this.date = date;
    }

    public Customer getCustomer() {
        return customer;
    }

    public void setCustomer(Customer customer) {
        this.customer = customer;
    }

    public Company getCompany() {
        return company;
    }

    public void setCompany(Company company) {
        this.company = company;
    }

    @Override
    public String toString() {
        return "Invoice {" +
                "\n\tid = " + id + "," +
                "\n\tdescription = '" + description + "'," +
                "\n\tamount = '" + amount + "'," +
                "\n\tdate = '" + date + "'," +
                "\n\tcustomer = " + customer + "," +
                "\n\tcompany = " + company +
                "\n}";
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof Invoice)) {
            return false;
        }

        Invoice invoice = (Invoice) o;

        if (Double.compare(invoice.amount, amount) != 0) {
            return false;
        }
        if (!id.equals(invoice.id)) {
            return false;
        }
        if (!description.equals(invoice.description)) {
            return false;
        }
        if (!date.equals(invoice.date)) {
            return false;
        }
        if (!customer.equals(invoice.customer)) {
            return false;
        }
        return company.equals(invoice.company);
    }

    @Override
    public int hashCode() {
        int result;
        long temp;
        result = id.hashCode();
        result = 31 * result + description.hashCode();
        temp = Double.doubleToLongBits(amount);
        result = 31 * result + (int) (temp ^ (temp >>> 32));
        result = 31 * result + date.hashCode();
        result = 31 * result + customer.hashCode();
        result = 31 * result + company.hashCode();
        return result;
    }
}
